# Imports go at the top
from microbit import *
import music
music.set_tempo(bpm=138)

while True:
    if pin0.is_touched():
        display.show("Y")
        #verse
        music.play('E4:2')
        music.play('F4:2')
        music.play('G4:2')
        music.play('A4:2')
        music.play('B4:4')
        music.play('E5:2')
        music.play('D5:2')
        music.play('B4:4')
        music.play('E4:4')
        music.play('B4:2')
        music.play('A4:2')
        music.play('G4:2')
        music.play('F4:2')
        music.play('E4:2')
        music.play('F4:2')
        music.play('G4:2')
        music.play('A4:2')
        music.play('B4:4')
        music.play('A4:4')
        music.play('G4:4')
        music.play('F4:2')
        music.play('E4:2')
        music.play('F4:2')
        music.play('G4:2')
        music.play('F4:2')
        music.play('E4:2')
        music.play('D3:2')
        music.play('F4:2')
        music.play('E4:2')
        music.play('F4:2')
        music.play('G4:2')
        music.play('A4:2')
        music.play('B4:4')
        music.play('E5:2')
        music.play('D5:2')
        music.play('B4:4')
        music.play('E4:4')
        music.play('B4:2')
        music.play('A4:2')
        music.play('G4:2')
        music.play('F4:2')
        music.play('E4:2')
        
        
        music.play('F4:2')
        music.play('G4:2')
        music.play('A4:2')
        music.play('B4:4')
        
        
        music.play('F4')
        music.play('G4')
        music.play('A4')
        music.play('B4')
        
        #bridge
        music.play('D4:2')
        music.play('E5:2')
        music.play('G4:2')
        music.play('A4:2')
        music.play('B4:4')
        music.play('A4:2')
        music.play('B4:2')
        
        music.play('D4:2')
        music.play('E5:2')
        music.play('G4:2')
        music.play('A4:2')
        music.play('B4:4')
        music.play('A4:2')
        music.play('B4:2')
        
        music.play('A4:2')
        music.play('G4:2')
        music.play('F4:2')
        music.play('D4:2')
        music.play('E4:4')
        music.play('D4:2')
        music.play('E4:2')
        
        music.play('F4:2')
        music.play('G4:2')
        music.play('A4:2')
        music.play('B4:2')
        music.play('E4:4')
        
        music.play('D5:2')
        music.play('E5:2')
        music.play('B4:2')
        music.play('A4:2')
        music.play('G4:4')
        
        music.play('A4:2')
        music.play('B4:2')
        
        music.play('D5:2')
        music.play('E5:2')
        music.play('G4:2')
        music.play('A4:2')
        music.play('G4:4')
        
        music.play('A4:2')
        music.play('B4:2')
        
        music.play('A4:2')
        music.play('G4:2')
        music.play('F4:2')
        music.play('D4:2')
        music.play('E4:4')
        
        music.play('D4:2')
        music.play('E4:2')
        
        music.play('F4:2')
        music.play('G4:2')
        music.play('A4:2')
        music.play('B4:2')
        music.play('E4:4')
        music.play('G4:2')
        music.play('D4:2')
        
        music.play('G5:2')
        music.play('F5:2')
        music.play('E5:2')
        music.play('D5:2')
        music.play('B4:4')
        music.play('A4:2')
        music.play('B4:2')
        
        music.play('D5:2')
        music.play('E5:2')
        music.play('B4:2')
        music.play('A4:2')
        music.play('B4:4')
        music.play('A4:2')
        music.play('G4:2')
        
        music.play('G5:2')
        music.play('F5:2')
        music.play('E5:2')
        music.play('D5:2')
        music.play('B4:4')
        music.play('A4:2')
        music.play('B4:2')
        
        music.play('A4:2')
        music.play('G4:2')
        music.play('F4:2')
        music.play('D4:2')
        music.play('E4:8')
    else:
        display.show("N")